version: 1
root:
  level: DEBUG
  handlers: [console]
loggers:
  pp.exceptions:
    level: DEBUG
    handlers: [pp.exceptions.fhandler, console]
    qualname: pp.exceptions
    propagate: false
  pp.progress:
    level: DEBUG
    handlers: [pp.progress.fhandler]
    qualname: pp.progress
    propagate: false
handlers:
  pp.exceptions.fhandler:
    class: logging.FileHandler
    filename: pp.exceptions.log
    formatter: simpleFormatter
    level: DEBUG
  pp.progress.fhandler:
    class: logging.FileHandler
    filename: pp.progress.log
    formatter: simpleFormatter
    level: DEBUG
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simpleFormatter
    level: DEBUG
formatters:
  simpleFormatter:
    class: logging.Formatter
    format: '%(name)s %(asctime)s %(levelname)s %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'